version: '3.5'

services:

    simple-web-service:
      image: devopsdockeruh/simple-web-service
      build: .
      volumes:
        - /home/DockerCourse/2_1_Exercise/text.log:/usr/src/app/text.log
      container_name: simple_web_service_with_compose