version: '3.5'

services:
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=myexample
      container_name: db_backend_2_10
    redis:
      image: redis
      build: .
      container_name: 2-10-redis
    backend:
      image: example-backend
      build: .
#      ports:
#        - 8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
#        - REQUEST_ORIGIN=http://localhost
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_PASSWORD=myexample
      container_name: 2-10-backend
      depends_on:
        - db
    frontend:
      image: example-frontend-2-10
      build: .
#      ports:
#        - 5000:5000
      container_name: 2-10-frontend
    web:
      image: nginx
      ports:
        - 80:80
      environment:
        - NGINX_HOST=http://localhost
        - NGINX_PORT=80
      volumes:
#        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./config.conf:/etc/nginx/nginx.conf
      depends_on:
        - backend
        - frontend
      container_name: 2-10-nginx