version: '3.7'

services:
  phonebook-dev-2-11:
    build: . # Build with the Dockerfile here
    command: npm run dev # Run npm run dev as the command
    ports:
      - 3001:3001 # The app uses port 3001 by default, publishing it in 3001 host port
    volumes:
      - ./:/usr/src/app # Let us modify the contents of the container locally
      - node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: phonebook-dev-2-11 # Container name for convenience

volumes: # This is required for the node_modules named volume
  node_modules: