version: '3.5'

services:
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=myexample
      container_name: db_backend
    redis:
      image: redis
      build: .
      container_name: 2-6-redis
    backend:
      image: example-backend
      build: .
      ports:
        - 8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_PASSWORD=myexample
      container_name: 2-6-backend
      depends_on:
        - db
    frontend:
      image: example-frontend
      build: .
      ports:
        - 5000:5000
      container_name: 2-6-frontend