version: '3.5'

services:
    redis:
      image: redis
      build: .
      container_name: 2-4-redis
    backend:
      image: example-backend
      build: .
      ports:
        - 8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redis
      container_name: 2-4-backend
    frontend:
      image: example-frontend
      build: .
      ports:
        - 5000:5000
      container_name: 2-4-frontend