version: '3.5'

services:
    backend:
      image: example-backend
      build: .
      ports:
        - 8080:8080
      environment:
        - REQUEST_ORIGIN=http://localhost:5000
      container_name: 2-3-backend
    frontend:
      image: example-frontend
      build: .
      ports:
        - 5000:5000
      container_name: 2-3-frontend